
# Makefile for misc devices that really don't fit anywhere else.
#
include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y += nt35521s_fhd720_dsi_vdo_truly.o
#obj-y += tps65132.o
#obj-y += Bl_lm3630a.o




