#ifndef __CUST_EINT_EXT_H__
#define __CUST_EINT_EXT_H__

/* Base EINT constants (if not defined elsewhere) */
#ifndef CUST_EINT_POLARITY_LOW
#define CUST_EINT_POLARITY_LOW       0
#endif
#ifndef CUST_EINT_POLARITY_HIGH
#define CUST_EINT_POLARITY_HIGH      1
#endif
#ifndef CUST_EINT_EDGE_SENSITIVE
#define CUST_EINT_EDGE_SENSITIVE     0
#endif
#ifndef CUST_EINT_LEVEL_SENSITIVE
#define CUST_EINT_LEVEL_SENSITIVE    1
#endif
#ifndef CUST_EINT_DEBOUNCE_DISABLE
#define CUST_EINT_DEBOUNCE_DISABLE   0
#endif
#ifndef CUST_EINT_DEBOUNCE_ENABLE
#define CUST_EINT_DEBOUNCE_ENABLE    1
#endif

/* Fingerprint sensor EINT (EINT 8 on F1s) */
#define CUST_EINT_FPC_NUM            8
#define CUST_EINT_FPC_DEBOUNCE_CN    0

/* Home key */
#define CUST_EINT_HOME_KEY_NUM       9

/* WiFi EINT */
#define CUST_EINT_WIFI_NUM           10
#define CUST_EINT_WIFI_POLARITY      CUST_EINT_POLARITY_LOW
#define CUST_EINT_WIFI_SENSITIVE     CUST_EINT_EDGE_SENSITIVE
#define CUST_EINT_WIFI_DEBOUNCE_CN  0
#define CUST_EINT_WIFI_DEBOUNCE_EN   CUST_EINT_DEBOUNCE_DISABLE

/* FM RDS */
#define CUST_EINT_FM_RDS_NUM         11
#define CUST_EINT_FM_RDS_POLARITY    CUST_EINT_POLARITY_LOW
#define CUST_EINT_FM_RDS_SENSITIVE   CUST_EINT_EDGE_SENSITIVE
#define CUST_EINT_FM_RDS_DEBOUNCE_CN 0
#define CUST_EINT_FM_RDS_DEBOUNCE_EN CUST_EINT_DEBOUNCE_DISABLE

/* NFC IRQ */
#define CUST_EINT_IRQ_NFC_NUM        12
#define CUST_EINT_IRQ_NFC_TYPE       CUST_EINT_EDGE_SENSITIVE
#define CUST_EINT_IRQ_NFC_DEBOUNCE_CN 0

/* HDMI HPD */
#define CUST_EINT_HDMI_HPD_NUM       13

/* MHL */
#define CUST_EINT_MHL_NUM            14
#define CUST_EINT_MHL_TYPE           CUST_EINT_EDGE_SENSITIVE
#define CUST_EINT_MHL_DEBOUNCE_CN    0

/* PMIC */
#define CUST_EINT_PMIC_DEBOUNCE_CN   0
#define CUST_EINT_PMIC_DEBOUNCE_EN   CUST_EINT_DEBOUNCE_DISABLE

/* Combo (WiFi/BT/GPS) */
#define CUST_EINT_COMBO_ALL_NUM      15
#define CUST_EINT_COMBO_ALL_TYPE     CUST_EINT_EDGE_SENSITIVE
#define CUST_EINT_COMBO_ALL_DEBOUNCE_CN 0
#define CUST_EINT_COMBO_ALL_DEBOUNCE_EN CUST_EINT_DEBOUNCE_DISABLE

#define CUST_EINT_COMBO_BGF_NUM      16
#define CUST_EINT_COMBO_BGF_POLARITY CUST_EINT_POLARITY_LOW
#define CUST_EINT_COMBO_BGF_SENSITIVE CUST_EINT_EDGE_SENSITIVE
#define CUST_EINT_COMBO_BGF_TYPE     CUST_EINT_EDGE_SENSITIVE
#define CUST_EINT_COMBO_BGF_DEBOUNCE_CN 0
#define CUST_EINT_COMBO_BGF_DEBOUNCE_EN CUST_EINT_DEBOUNCE_DISABLE

/* SWTP (Smart Watch Touch Panel) */
#define CUST_EINT_SWTP_NUM           17
#define CUST_EINT_SWTP_TYPE          CUST_EINT_EDGE_SENSITIVE
#define CUST_EINT_SWTP_DEBOUNCE_CN   0
#define CUST_EINT_SWTP_2_NUM         18
#define CUST_EINT_SWTP_2_TYPE        CUST_EINT_EDGE_SENSITIVE
#define CUST_EINT_SWTP_2_DEBOUNCE_CN 0

/* VDC */
#define CUST_EINT_VDC_NUM            19
#define CUST_EINT_VDC_DEBOUNCE_CN    0

/* SensorHub */
#define CUST_EINT_SENSORHUB_NUM      20
#define CUST_EINT_SENSORHUB_WAKE_UP_NUM 21
#define CUST_EINT_SENSORHUB_DEBOUNCE_CN 0

/* LSM6DS3 sensor */
#define CUST_EINT_LSM6DS3_NUM        22
#define CUST_EINT_LSM6DS3_TYPE       CUST_EINT_EDGE_SENSITIVE
#define CUST_EINT_LSM6DS3_DEBOUNCE_CN 0

/* Ext Buck OC */
#define CUST_EINT_EXT_BUCK_OC_NUM    23
#define CUST_EINT_EXT_BUCK_OC_TYPE   CUST_EINT_EDGE_SENSITIVE
#define CUST_EINT_EXT_BUCK_OC_DEBOUNCE_CN 0
#define CUST_EINT_EXT_BUCK_OC_DEBOUNCE_EN CUST_EINT_DEBOUNCE_DISABLE

/* KPD Slide */
#define CUST_EINT_KPD_SLIDE_NUM      24
#define CUST_EINT_KPD_SLIDE_POLARITY CUST_EINT_POLARITY_LOW
#define CUST_EINT_KPD_SLIDE_SENSITIVE CUST_EINT_EDGE_SENSITIVE
#define CUST_EINT_KPD_SLIDE_DEBOUNCE_CN 0

/* External modem EINTs */
#define CUST_EINT_DT_EXT_MD_EXP_NUM    25
#define CUST_EINT_DT_EXT_MD_EXP_TYPE   CUST_EINT_EDGE_SENSITIVE
#define CUST_EINT_DT_EXT_MD_EXP_DEBOUNCE_CN 0

#define CUST_EINT_DT_EXT_MD_WDT_NUM    26
#define CUST_EINT_DT_EXT_MD_WDT_POLARITY CUST_EINT_POLARITY_LOW
#define CUST_EINT_DT_EXT_MD_WDT_SENSITIVE CUST_EINT_EDGE_SENSITIVE
#define CUST_EINT_DT_EXT_MD_WDT_TYPE   CUST_EINT_EDGE_SENSITIVE
#define CUST_EINT_DT_EXT_MD_WDT_DEBOUNCE_CN 0

#define CUST_EINT_DT_EXT_MD_WK_UP_NUM    27
#define CUST_EINT_DT_EXT_MD_WK_UP_POLARITY CUST_EINT_POLARITY_LOW
#define CUST_EINT_DT_EXT_MD_WK_UP_SENSITIVE CUST_EINT_EDGE_SENSITIVE
#define CUST_EINT_DT_EXT_MD_WK_UP_DEBOUNCE_CN 0

/* EVDO external modem */
#define CUST_EINT_EVDO_DT_EXT_MDM_ACK_NUM         28
#define CUST_EINT_EVDO_DT_EXT_MDM_ACK_DEBOUNCE_EN  CUST_EINT_DEBOUNCE_DISABLE
#define CUST_EINT_EVDO_DT_EXT_MDM_FLOW_CTRL_NUM    29
#define CUST_EINT_EVDO_DT_EXT_MDM_FLOW_CTRL_DEBOUNCE_EN CUST_EINT_DEBOUNCE_DISABLE
#define CUST_EINT_EVDO_DT_EXT_MDM_RDY_NUM          30
#define CUST_EINT_EVDO_DT_EXT_MDM_RDY_DEBOUNCE_EN  CUST_EINT_DEBOUNCE_DISABLE
#define CUST_EINT_EVDO_DT_EXT_MDM_RST_IND_NUM      31
#define CUST_EINT_EVDO_DT_EXT_MDM_RST_IND_DEBOUNCE_EN CUST_EINT_DEBOUNCE_DISABLE
#define CUST_EINT_EVDO_DT_EXT_MDM_WAKE_AP_NUM      32
#define CUST_EINT_EVDO_DT_EXT_MDM_WAKE_AP_DEBOUNCE_EN CUST_EINT_DEBOUNCE_DISABLE

/* PMIC MT6311/MT6325 */
#define CUST_EINT_MT_PMIC_MT6311_NUM   33
#define CUST_EINT_MT_PMIC_MT6325_NUM   34

/* MT6280 USB wakeup */
#define CUST_EINT_MT6280_USB_WAKEUP_NUM 35

/* MCU AP data */
#define CUST_EINT_MCU_AP_DATA          36

/* Touch panel type (used by some HALs) */
#define CUST_EINT_TOUCH_PANEL_NUM        0
#define CUST_EINT_TOUCH_PANEL_POLARITY   CUST_EINT_POLARITY_LOW
#define CUST_EINT_TOUCH_PANEL_SENSITIVE CUST_EINT_EDGE_SENSITIVE
#define CUST_EINT_TOUCH_PANEL_TYPE       CUST_EINT_EDGE_SENSITIVE
#define CUST_EINT_TOUCH_PANEL_DEBOUNCE_CN 0
#define CUST_EINT_TOUCH_PANEL_DEBOUNCE_EN CUST_EINT_DEBOUNCE_DISABLE

/* ALS type */
#define CUST_EINT_ALS_NUM          1
#define CUST_EINT_ALS_POLARITY     CUST_EINT_POLARITY_LOW
#define CUST_EINT_ALS_SENSITIVE    CUST_EINT_EDGE_SENSITIVE
#define CUST_EINT_ALS_TYPE         CUST_EINT_EDGE_SENSITIVE
#define CUST_EINT_ALS_DEBOUNCE_CN  0
#define CUST_EINT_ALS_DEBOUNCE_EN  CUST_EINT_DEBOUNCE_DISABLE

/* ACCDET type */
#define CUST_EINT_ACCDET_NUM       4
#define CUST_EINT_ACCDET_TYPE      CUST_EINT_EDGE_SENSITIVE
#define CUST_EINT_ACCDET_DEBOUNCE_CN 0
#define CUST_EINT_ACCDET_DEBOUNCE_EN CUST_EINT_DEBOUNCE_DISABLE

/* Hall sensor */
#define CUST_EINT_HALL_1_NUM       7

#endif
