#ifndef __CUST_CLK_BUF_H__
#define __CUST_CLK_BUF_H__

#define CLKBUF_MAX_COUNT 4

/* Clock buffer status enums (for legacy mode - normally in mt_clkbuf_ctl.h) */
#ifndef CLOCK_BUFFER_DISABLE
#define CLOCK_BUFFER_DISABLE       0
#endif
#ifndef CLOCK_BUFFER_SW_CONTROL
#define CLOCK_BUFFER_SW_CONTROL    1
#endif
#ifndef CLOCK_BUFFER_HW_CONTROL
#define CLOCK_BUFFER_HW_CONTROL    2
#endif

/* Driving current enums (for legacy mode) */
#ifndef CLK_BUF_DRIVING_CURR_0_4MA
#define CLK_BUF_DRIVING_CURR_0_4MA  0
#endif
#ifndef CLK_BUF_DRIVING_CURR_0_9MA
#define CLK_BUF_DRIVING_CURR_0_9MA  1
#endif
#ifndef CLK_BUF_DRIVING_CURR_1_4MA
#define CLK_BUF_DRIVING_CURR_1_4MA  2
#endif
#ifndef CLK_BUF_DRIVING_CURR_1_9MA
#define CLK_BUF_DRIVING_CURR_1_9MA  3
#endif

/* BSI clock buffer status */
#define CLK_BUF1_STATUS  CLOCK_BUFFER_SW_CONTROL
#define CLK_BUF2_STATUS  CLOCK_BUFFER_SW_CONTROL
#define CLK_BUF3_STATUS  CLOCK_BUFFER_DISABLE
#define CLK_BUF4_STATUS  CLOCK_BUFFER_DISABLE

/* RF clock buffer driving current */
#define RF_CLK_BUF1_DRIVING_CURR  CLK_BUF_DRIVING_CURR_1_4MA
#define RF_CLK_BUF2_DRIVING_CURR  CLK_BUF_DRIVING_CURR_1_4MA
#define RF_CLK_BUF3_DRIVING_CURR  CLK_BUF_DRIVING_CURR_1_4MA
#define RF_CLK_BUF4_DRIVING_CURR  CLK_BUF_DRIVING_CURR_1_4MA

/* PMIC clock buffer status */
#define CLK_BUF5_STATUS_PMIC  CLOCK_BUFFER_HW_CONTROL
#define CLK_BUF6_STATUS_PMIC  CLOCK_BUFFER_SW_CONTROL
#define CLK_BUF7_STATUS_PMIC  CLOCK_BUFFER_SW_CONTROL
#define CLK_BUF8_STATUS_PMIC  CLOCK_BUFFER_HW_CONTROL

/* PMIC clock buffer driving current */
#ifndef PMIC_CLK_BUF5_DRIVING_CURR
#define PMIC_CLK_BUF5_DRIVING_CURR  CLK_BUF_DRIVING_CURR_1_4MA
#endif
#ifndef PMIC_CLK_BUF6_DRIVING_CURR
#define PMIC_CLK_BUF6_DRIVING_CURR  CLK_BUF_DRIVING_CURR_1_4MA
#endif
#ifndef PMIC_CLK_BUF7_DRIVING_CURR
#define PMIC_CLK_BUF7_DRIVING_CURR  CLK_BUF_DRIVING_CURR_1_4MA
#endif
#ifndef PMIC_CLK_BUF8_DRIVING_CURR
#define PMIC_CLK_BUF8_DRIVING_CURR  CLK_BUF_DRIVING_CURR_1_4MA
#endif

#endif
