#ifndef __PMIC_DRV_H__
#define __PMIC_DRV_H__

/* Direct integer values - MT6351 PMIC LDO enum */
#define PMIC_APP_MAIN_CAMERA_POWER_A  4
#define PMIC_APP_MAIN_CAMERA_POWER_D  12
#define PMIC_APP_MAIN_CAMERA_POWER_AF 28
#define PMIC_APP_MAIN_CAMERA_POWER_IO 16
#define PMIC_APP_SUB_CAMERA_POWER_D   12
#define PMIC_APP_MAIN_CAMERA_POWER_A2 30
#define PMIC_APP_MAIN_CAMERA_POWER_D2 16

#endif
