#ifndef __CUST_GPIO_USAGE_H__
#define __CUST_GPIO_USAGE_H__

#define GPIO_CTP_EINT_PIN         GPIO1
#define GPIO_CTP_EINT_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_CTP_EINT_PIN_M_EINT   GPIO_MODE_02

#define GPIO_ACCDET_EINT_PIN         GPIO1
#define GPIO_ACCDET_EINT_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_ACCDET_EINT_PIN_M_EINT   GPIO_MODE_02

#define GPIO_MSDC1_INSI         GPIO1
#define GPIO_MSDC1_INSI_M_GPIO   GPIO_MODE_00

#define GPIO_GYRO_EINT_PIN         GPIO1
#define GPIO_GYRO_EINT_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_GYRO_EINT_PIN_M_EINT   GPIO_MODE_02

#define GPIO_LCD_ENN         GPIO1
#define GPIO_LCD_ENN_M_GPIO   GPIO_MODE_00

#define GPIO_ALS_EINT_PIN         GPIO1
#define GPIO_ALS_EINT_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_ALS_EINT_PIN_M_EINT   GPIO_MODE_02

#define GPIO_HALL_1_PIN         GPIO1
#define GPIO_HALL_1_PIN_M_GPIO   GPIO_MODE_00

#define GPIO_FLASH_LED_EN         GPIO1
#define GPIO_FLASH_LED_EN_M_GPIO   GPIO_MODE_00

#define GPIO_TORCH_EN         GPIO1
#define GPIO_TORCH_EN_M_GPIO   GPIO_MODE_00

#define GPIO_CTP_RST_PIN         GPIO1
#define GPIO_CTP_RST_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_CTP_RST_PIN_M_EINT   GPIO_MODE_02

#define GPIO_LCM_LED_EN         GPIO1
#define GPIO_LCM_LED_EN_M_GPIO   GPIO_MODE_00

#define GPIO_LCD_ENP         GPIO1
#define GPIO_LCD_ENP_M_GPIO   GPIO_MODE_00

#define GPIO_TF_EN         GPIO1
#define GPIO_TF_EN_M_GPIO   GPIO_MODE_00

#define GPIO_FDD_BAND_SUPPORT_DETECT_1ST_PIN         GPIO1
#define GPIO_FDD_BAND_SUPPORT_DETECT_1ST_PIN_M_GPIO   GPIO_MODE_00

#define GPIO_FDD_BAND_SUPPORT_DETECT_2ND_PIN         GPIO1
#define GPIO_FDD_BAND_SUPPORT_DETECT_2ND_PIN_M_GPIO   GPIO_MODE_00

#define GPIO_FDD_BAND_SUPPORT_DETECT_3RD_PIN         GPIO1
#define GPIO_FDD_BAND_SUPPORT_DETECT_3RD_PIN_M_GPIO   GPIO_MODE_00

#define GPIO_FPC_EINT_PIN         GPIO1
#define GPIO_FPC_EINT_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_FPC_EINT_PIN_M_EINT   GPIO_MODE_02

#define GPIO_TP_ID2         GPIO1
#define GPIO_TP_ID2_M_GPIO   GPIO_MODE_00

#define GPIO_FDD_BAND_SUPPORT_DETECT_4TH_PIN         GPIO1
#define GPIO_FDD_BAND_SUPPORT_DETECT_4TH_PIN_M_GPIO   GPIO_MODE_00

#define GPIO_TP_ID1         GPIO1
#define GPIO_TP_ID1_M_GPIO   GPIO_MODE_00

#define GPIO_HOME_PIN         GPIO1
#define GPIO_HOME_PIN_M_GPIO   GPIO_MODE_00

#define GPIO_OTG_IDDIG_EINT_PIN         GPIO1
#define GPIO_OTG_IDDIG_EINT_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_OTG_IDDIG_EINT_PIN_M_EINT   GPIO_MODE_02
#define GPIO_OTG_IDDIG_EINT_PIN_M_IDDIG GPIO_MODE_01

#define GPIO_0_DEPOP_SWITCH         GPIO1
#define GPIO_0_DEPOP_SWITCH_M_GPIO   GPIO_MODE_00

#define GPIO_NXPSPA_I2S_BCK_PIN         GPIO1
#define GPIO_NXPSPA_I2S_BCK_PIN_M_GPIO   GPIO_MODE_00

#define GPIO_NXPSPA_I2S_LRCK_PIN         GPIO1
#define GPIO_NXPSPA_I2S_LRCK_PIN_M_GPIO   GPIO_MODE_00

#define GPIO_NXPSPA_I2S_DATAOUT_PIN         GPIO1
#define GPIO_NXPSPA_I2S_DATAOUT_PIN_M_GPIO   GPIO_MODE_00

#define GPIO_MSDC1_CLK         GPIO1
#define GPIO_MSDC1_CLK_M_GPIO   GPIO_MODE_00
#define GPIO_MSDC1_CLK_M_MC1_CK   GPIO_MODE_01

#define GPIO_MSDC1_DAT3         GPIO1
#define GPIO_MSDC1_DAT3_M_GPIO   GPIO_MODE_00
#define GPIO_MSDC1_DAT3_M_MC1_DA3   GPIO_MODE_01

#define GPIO_MSDC1_CMD         GPIO1
#define GPIO_MSDC1_CMD_M_GPIO   GPIO_MODE_00
#define GPIO_MSDC1_CMD_M_MC1_CMD   GPIO_MODE_01

#define GPIO_MSDC1_DAT0         GPIO1
#define GPIO_MSDC1_DAT0_M_GPIO   GPIO_MODE_00
#define GPIO_MSDC1_DAT0_M_MC1_DA0   GPIO_MODE_01

#define GPIO_MSDC1_DAT2         GPIO1
#define GPIO_MSDC1_DAT2_M_GPIO   GPIO_MODE_00
#define GPIO_MSDC1_DAT2_M_MC1_DA2   GPIO_MODE_01

#define GPIO_MSDC1_DAT1         GPIO1
#define GPIO_MSDC1_DAT1_M_GPIO   GPIO_MODE_00
#define GPIO_MSDC1_DAT1_M_MC1_DA1   GPIO_MODE_01

#define GPIO_SIM2_SIO         GPIO1
#define GPIO_SIM2_SIO_M_GPIO   GPIO_MODE_00
#define GPIO_SIM2_SIO_M_SIM   GPIO_MODE_01

#define GPIO_SIM2_SRST         GPIO1
#define GPIO_SIM2_SRST_M_GPIO   GPIO_MODE_00
#define GPIO_SIM2_SRST_M_EINT   GPIO_MODE_02

#define GPIO_SIM2_SCLK         GPIO1
#define GPIO_SIM2_SCLK_M_GPIO   GPIO_MODE_00
#define GPIO_SIM2_SCLK_M_CLK   GPIO_MODE_01

#define GPIO_SIM1_SCLK         GPIO1
#define GPIO_SIM1_SCLK_M_GPIO   GPIO_MODE_00
#define GPIO_SIM1_SCLK_M_CLK   GPIO_MODE_01

#define GPIO_SIM1_SRST         GPIO1
#define GPIO_SIM1_SRST_M_GPIO   GPIO_MODE_00
#define GPIO_SIM1_SRST_M_EINT   GPIO_MODE_02

#define GPIO_SIM1_SIO         GPIO1
#define GPIO_SIM1_SIO_M_GPIO   GPIO_MODE_00
#define GPIO_SIM1_SIO_M_SIM   GPIO_MODE_01

#define GPIO_DSI_TE_PIN         GPIO1
#define GPIO_DSI_TE_PIN_M_GPIO   GPIO_MODE_00

#define GPIO_SIM2_HOT_PLUG         GPIO1
#define GPIO_SIM2_HOT_PLUG_M_GPIO   GPIO_MODE_00

#define GPIO_SIM1_HOT_PLUG         GPIO1
#define GPIO_SIM1_HOT_PLUG_M_GPIO   GPIO_MODE_00

#define GPIO_I2C3_SCA_PIN         GPIO1
#define GPIO_I2C3_SCA_PIN_M_GPIO   GPIO_MODE_00

#define GPIO_I2C3_SDA_PIN         GPIO1
#define GPIO_I2C3_SDA_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_I2C3_SDA_PIN_M_SDA   GPIO_MODE_01

#define GPIO_VEFUSE_LDO_EN         GPIO1
#define GPIO_VEFUSE_LDO_EN_M_GPIO   GPIO_MODE_00

#define GPIO_FPC_RESET_PIN         GPIO1
#define GPIO_FPC_RESET_PIN_M_GPIO   GPIO_MODE_00

#define GPIO_NXPSPA_I2S_DATAIN_PIN         GPIO1
#define GPIO_NXPSPA_I2S_DATAIN_PIN_M_GPIO   GPIO_MODE_00

#define GPIO_EXT_PMIC_EN         GPIO1
#define GPIO_EXT_PMIC_EN_M_GPIO   GPIO_MODE_00

#define GPIO_FPC_ID2_PIN         GPIO1
#define GPIO_FPC_ID2_PIN_M_GPIO   GPIO_MODE_00

#define GPIO_SMARTPA_RST_PIN         GPIO1
#define GPIO_SMARTPA_RST_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_SMARTPA_RST_PIN_M_EINT   GPIO_MODE_02

#define GPIO_FPC_ID1_PIN         GPIO1
#define GPIO_FPC_ID1_PIN_M_GPIO   GPIO_MODE_00

#define GPIO_I2C1_SDA_PIN         GPIO1
#define GPIO_I2C1_SDA_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_I2C1_SDA_PIN_M_SDA   GPIO_MODE_01

#define GPIO_I2C0_SDA_PIN         GPIO1
#define GPIO_I2C0_SDA_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_I2C0_SDA_PIN_M_SDA   GPIO_MODE_01

#define GPIO_I2C0_SCA_PIN         GPIO1
#define GPIO_I2C0_SCA_PIN_M_GPIO   GPIO_MODE_00

#define GPIO_I2C1_SCA_PIN         GPIO1
#define GPIO_I2C1_SCA_PIN_M_GPIO   GPIO_MODE_00

#define GPIO_SPI_MISO_PIN         GPIO1
#define GPIO_SPI_MISO_PIN_M_GPIO   GPIO_MODE_00

#define GPIO_SPI_CS_PIN         GPIO1
#define GPIO_SPI_CS_PIN_M_GPIO   GPIO_MODE_00

#define GPIO_SPI_MOSI_PIN         GPIO1
#define GPIO_SPI_MOSI_PIN_M_GPIO   GPIO_MODE_00

#define GPIO_SPI_SCK_PIN         GPIO1
#define GPIO_SPI_SCK_PIN_M_GPIO   GPIO_MODE_00

#define GPIO_SWCHARGER_EN_PIN         GPIO1
#define GPIO_SWCHARGER_EN_PIN_M_GPIO   GPIO_MODE_00

#define GPIO_EINT_CHG_STAT_PIN         GPIO1
#define GPIO_EINT_CHG_STAT_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_EINT_CHG_STAT_PIN_M_EINT   GPIO_MODE_02

#define GPIO_KPD_KCOL0_PIN         GPIO1
#define GPIO_KPD_KCOL0_PIN_M_GPIO   GPIO_MODE_00

#define GPIO_KPD_KCOL1_PIN         GPIO1
#define GPIO_KPD_KCOL1_PIN_M_GPIO   GPIO_MODE_00

#define GPIO_CAMERA_CMPDN_PIN         GPIO1
#define GPIO_CAMERA_CMPDN_PIN_M_GPIO   GPIO_MODE_00

#define GPIO_CAMERA_CMPDN1_PIN         GPIO1
#define GPIO_CAMERA_CMPDN1_PIN_M_GPIO   GPIO_MODE_00

#define GPIO_CAMERA_CMRST_PIN         GPIO1
#define GPIO_CAMERA_CMRST_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_CAMERA_CMRST_PIN_M_EINT   GPIO_MODE_02

#define GPIO_CAMERA_CMRST1_PIN         GPIO1
#define GPIO_CAMERA_CMRST1_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_CAMERA_CMRST1_PIN_M_EINT   GPIO_MODE_02

#define GPIO_I2C2_SCA_PIN         GPIO1
#define GPIO_I2C2_SCA_PIN_M_GPIO   GPIO_MODE_00

#define GPIO_I2C2_SDA_PIN         GPIO1
#define GPIO_I2C2_SDA_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_I2C2_SDA_PIN_M_SDA   GPIO_MODE_01

#define GPIO_GPS_LNA_PIN         GPIO1
#define GPIO_GPS_LNA_PIN_M_GPIO   GPIO_MODE_00

#define GPIO_AUD_DAT_MOSI_PIN         GPIO1
#define GPIO_AUD_DAT_MOSI_PIN_M_GPIO   GPIO_MODE_00

#define GPIO_AUD_DAT_MISO_PIN         GPIO1
#define GPIO_AUD_DAT_MISO_PIN_M_GPIO   GPIO_MODE_00

#define GPIO_LCM_RST         GPIO1
#define GPIO_LCM_RST_M_GPIO   GPIO_MODE_00
#define GPIO_LCM_RST_M_EINT   GPIO_MODE_02

#define GPIO_MSDC0_DAT0         GPIO1
#define GPIO_MSDC0_DAT0_M_GPIO   GPIO_MODE_00

#define GPIO_MSDC0_CLK         GPIO1
#define GPIO_MSDC0_CLK_M_GPIO   GPIO_MODE_00

#define GPIO_MSDC0_CMD         GPIO1
#define GPIO_MSDC0_CMD_M_GPIO   GPIO_MODE_00

#define GPIO_MSDC0_DAT1         GPIO1
#define GPIO_MSDC0_DAT1_M_GPIO   GPIO_MODE_00

#define GPIO_MSDC0_DAT5         GPIO1
#define GPIO_MSDC0_DAT5_M_GPIO   GPIO_MODE_00

#define GPIO_MSDC0_DAT6         GPIO1
#define GPIO_MSDC0_DAT6_M_GPIO   GPIO_MODE_00

#define GPIO_MSDC0_DAT4         GPIO1
#define GPIO_MSDC0_DAT4_M_GPIO   GPIO_MODE_00

#define GPIO_MSDC0_RSTB         GPIO1
#define GPIO_MSDC0_RSTB_M_GPIO   GPIO_MODE_00
#define GPIO_MSDC0_RSTB_M_EINT   GPIO_MODE_02

#define GPIO_MSDC0_DAT2         GPIO1
#define GPIO_MSDC0_DAT2_M_GPIO   GPIO_MODE_00

#define GPIO_MSDC0_DAT3         GPIO1
#define GPIO_MSDC0_DAT3_M_GPIO   GPIO_MODE_00

#define GPIO_MSDC0_DAT7         GPIO1
#define GPIO_MSDC0_DAT7_M_GPIO   GPIO_MODE_00

#define GPIO_MSDC0_DSL         GPIO1
#define GPIO_MSDC0_DSL_M_GPIO   GPIO_MODE_00

#endif
